name: WaterPrepared
favicon: null
layout_spectrum: 0.97245
typography_spectrum: 0.4833
title: 'Emergency Water Storage | Emergency Water Tanks'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4353d8'
    - '#293086'
    - '#000000'
    - '#5b7af2'
    - '#aaaaaa'
  brandStrength: 0.3587461190763861
  lightness: 0.2291011973284185
  saturation: 0.36134804296307266
  rhythmicContrast: 0.891532298643142
purpose: []
